### ISSUE TITLE
Avoid using react-broadcast (or make a flux / redux compatible)

### ISSUE THREAD

**Issue by jasonm23** [TrueCar/react-launch-darkly#21]

**Comment by jacobmoretti** [comment]
@jasonm23 Thanks for the suggestion! This is definitely something I've been thinking about. It will be something we need to move towards in order to tackle: #15

**Comment by jacobmoretti** [comment]
@jasonm23 After thinking about this more, we probably won't be moving forward with using a dependency like redux any time soon. Even for supporting a feature such as bootstrapping flag values, redux is over-kill. In terms of avoiding react-broadcast for our use-case, do you mind elaborating on why?

**Comment by jasonm23** [comment]
The primary motivation for this suggestion was to make components that used react-launch-darkly easier to test.  In particular, when building "sociable" tests. (i.e. small scale integration test of related components.  In contrast to end to end testing)

That said ensuring that the launch darkly feature switching was operational would be unnecessary usually (low value test.)  

Faking/Mocking out launch-darkly was the testing direction we went in on the project at hand when I posted this.

I think there is probably room for a similar component which targets redux / flux centric projects.  However I respect your choice not to go in that direction.  There's always more than one way to do things.

Thanks for considering the idea.

**Comment by jacobmoretti** [comment]
Thanks for the reply!

I'm definitely curious about your use case though. We haven't even tagged a version 1 of this library yet, mostly been outlining and solving our internal use-cases first. But we're always looking for outside feedback to getting it to a stronger and well-poised v1.

**Comment by jasonm23** [comment]
So for my project it was decided that we'd implement our own wrapper of ldclient.

It worked better for our flux based architecture (p-flux)

Using this technique it removed the need for a component to manage LD.
