### ISSUE TITLE
How to set the base Url for launchdarkly?

### ISSUE THREAD

**Issue by sikka** [TrueCar/react-launch-darkly#35]
We have our own instance at our company. I have to set the url to "https://app.abc.launchdarkly.com". How do I do that?

**Comment by jacobmoretti** [comment]
I wasn't even aware this feature was supported by the js ldclient. It's undocumented on their end but digging through their source, it seems they accept options to define `baseUrl`: https://github.com/launchdarkly/js-client/blob/master/src/index.js#L241

Currently this isn't supported, but you're welcome to submit a PR. I can point you in the general direction for this:
- [`ldClientWrapper`](https://github.com/TrueCar/react-launch-darkly/blob/master/src/lib/utils.js#L17) would need to accept an additional `options` arg where `baseUrl` would be a property
- Then `options` would need to be passed from [`LaunchDarkly`](https://github.com/TrueCar/react-launch-darkly/blob/master/src/components/LaunchDarkly.js#L15) down to [`FeatureFlag`](https://github.com/TrueCar/react-launch-darkly/blob/master/src/components/FeatureFlag.js#L17)

I'll create a separate issue to track this as a feature request.

**Comment by jacobmoretti** [comment]
__Closed__ See https://github.com/TrueCar/react-launch-darkly/issues/41
