### ISSUE TITLE
Support setting `baseUrl` when initializing `LaunchDarkly`

### ISSUE THREAD

**Issue by jacobmoretti** [TrueCar/react-launch-darkly#41]
LaunchDarkly offers in-house instances to some customers. In order to support this, we'd need to open our ld client initialization to accept an `options` arg where `baseUrl` is defined.

## Potential Implementation
`options` arg:
https://github.com/launchdarkly/js-client/blob/master/src/index.js#L241

- [`ldClientWrapper`](https://github.com/TrueCar/react-launch-darkly/blob/master/src/lib/utils.js#L17) would need to accept an additional `options` arg where `baseUrl` would be a property
- Then `options` would need to be passed from [`LaunchDarkly`](https://github.com/TrueCar/react-launch-darkly/blob/master/src/components/LaunchDarkly.js#L15) down to [`FeatureFlag`](https://github.com/TrueCar/react-launch-darkly/blob/master/src/components/FeatureFlag.js#L17)

**Comment by sikka** [comment]
@jacobmoretti  - can you please review the PR above?

**Comment by jacobmoretti** [comment]
Will be resolved by https://github.com/TrueCar/react-launch-darkly/pull/45
