### ISSUE TITLE
RenderFeatureCallback does not fire for false feature flags

### ISSUE THREAD

**Issue by laij84** [TrueCar/react-launch-darkly#59]
I have setup a simple boolean feature, true = return blue button, false = return red button. If i configure the default rule to return the true variation (blue button), it works. However if I configure the default to serve the false variation (red button), the callback does not seem to fire at all. How can I get this to work?

**Comment by jacobmoretti** [comment]
Hi @laij84, you'll want to look at using the `renderDefaultCallback` prop: https://github.com/TrueCar/react-launch-darkly#renderdefaultcallback--function-optional. Let me know if that works for you, thanks!

**Comment by laij84** [comment]
Hi Jacob,

Thanks that did the trick.

**Comment by jacobmoretti** [comment]
Awesome glad to hear that. Closing this issue since its been resolved.
