### ISSUE TITLE
Supporting changing user context

### ISSUE THREAD

**Issue by breeny** [TrueCar/react-launch-darkly#60]
Is this something on the roadmap or currently supported? Looking to support both anonymous and logged in feature toggling with this. Thanks!

**Comment by jacobmoretti** [comment]
So far we haven't needed this functionality at TrueCar but I can definitely look into adding it this week. I'm also more than willing to look at a PR if you wanted to take a stab at it.

For some direction, I'd take a look at how the [getAllFeatureFlags()](https://github.com/TrueCar/react-launch-darkly/blob/master/src/lib/utils.js#L82-L89) function is setup. Its just a thin wrapper around [LaunchDarkly's js client](https://github.com/launchdarkly/js-client) and calls the necessary function on the client. A similar method can be used to achieve changing the user context.

**Comment by jacobmoretti** [comment]
@breeny Wanted to give an update on this, haven't had a chance to squeeze this one in. Unfortunately this has been on the bottom of the priorities for this repo. Hoping to get this one in the next week or so.

**Comment by jacobmoretti** [comment]
The `identify` functionality has been added with the latest release: https://github.com/TrueCar/react-launch-darkly/releases/tag/v1.4.0. Closing this issue now.
