### ISSUE TITLE
Flag always evaluates as false

### ISSUE THREAD

**Issue by pixelstew** [TrueCar/react-launch-darkly#70]
This is odd and I have logged a ticket with LD too. 
I have implemented a basic flag to test the lib out. 

```
<LaunchDarkly clientId="xxxxx" user={{ key: "xxxx" }}>
  <React.Fragment>
          .....
          <FeatureFlag
            flagKey="dummy-flag"
            renderFeatureCallback={this.renderFeature}
          />     
         ....      
  </React.Fragment>
</LaunchDarkly>
```
The debugger in LD registers the flag when I navigate to the view it sits in. However despite it registering the correct flag and the correct user id - it always evaluates as false for the user (despite the flag being set to eval true for my user id, all checked and checked again). I have tried this on multiple users and multiple flags.

Is this something that has been seen before?

**Comment by jacobmoretti** [comment]
@pixelstew Noticed you closed this but did you find a solution?

**Comment by pixelstew** [comment]
Yeah, I didn’t have full write access so hadn’t noticed the flag didn’t
have the ‘use JavaScript sdk’ option checked. Once I had the admin account,
sorted it in 10 seconds.

One of those silly ones I’m afraid.

Thanks for getting back

**Comment by jacobmoretti** [comment]
Ahh no worries, we had the same issue here at TrueCar when we first started using LD. It was really easy to overlook that little checkbox.
