### ISSUE TITLE
Replace React-Broadcast with React Context

### ISSUE THREAD

**Issue by georgeciubotaru** [TrueCar/react-launch-darkly#71]

**Comment by georgeciubotaru** [comment]
I can offer my support to make this happen.

**Comment by sethbattin** [comment]
I'd say go for it.  My only concern here would be the possibility of users stuck on old versions of React losing out on future updates.  On the other hand, hopefully this library is not the largest problem that those apps face.  Worst case, they could fork an old release and re-apply patches.

Speaking of that tactic, the `react-broadcast` mechanism is confined mostly to the components `LaunchDarkly` and `FeatureFlag`.  So this proposed change should be possible without touching the bulk of the other logic.  Please try to make the change as minimal as possible.  It will be easier to merge that way too, of course :)

Obviously it will require attention to `package.json` to update the minimum requirements as well.  New major version, here we come.

**Comment by sethbattin** [comment]
implemented by https://github.com/TrueCar/react-launch-darkly/pull/72
