### ISSUE TITLE
Is there a way to create LD users?

### ISSUE THREAD

**Issue by samuelcastro** [TrueCar/react-launch-darkly#97]
When doing:
```
<LaunchDarkly
      clientId={LD_CLIENT_SIDE_ID}
      user={{ key: '123', name: 'test' }}
    >
...
</LaunchDarkly>
```
Is there a way to create that user on LD?

**Comment by samuelcastro** [comment]
nvm, my mistake.

**Comment by sethbattin** [comment]
Self-answered, but for posterity:

https://docs.launchdarkly.com/docs/targeting-users
> While the Targeting tab uses the language of targeted "users", a user can be any identifier that uniquely corresponds to a target. You can target users of your application, email addresses, systems, services, machines, resources, or anything else that can be uniquely identified.
